### ISSUE TITLE
CLI for aggregated proving

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/proof-market-toolchain#124]
We need a way for users to use the aggregated mode of our proof system. Since it requires to run multiple provers, it's quite complex comparing to how we run the usual prover.

CLI for aggregated prover has to provide the same interface for different ways of aggregated prover running:

- aggregated proving on proof market
- aggregated local proving

**Comment by akokoshn** [comment]
Double check if all scripts for aggregated proving are ready

**Comment by karakazyablek** [comment]
TODO: update the task if it's still actual

**Comment by akokoshn** [comment]
@Rolaman , could you please double check what we need to add in proof-market for support aggregation?
