### ISSUE TITLE
Support of different arithmetization params

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/proof-market-toolchain#127]
We need to have the ability to pass different arithmetization params through our CLI. These arithmetization params will be part of the statement and will be the same for all the requests for a given statement.

Arithmetization params include (default values shown):
- String parameter (possible values: PALLAS, BLS12_381): BLUEPRINT_FIELD=PALLAS
- Integer parameter: WITNESS_COLUMNS=10
- Integer parameter: PUBLIC_INPUT_COLUMNS=2
- Integer parameter: CONSTANT_COLUMNS=7
- Integer parameter: SELECTOR_COLUMNS=5
- Integer parameter: SECURITY_PARAMETER_LAMBDA=40
- Integer parameter: SECURITY_PARAMETER_GRINDING_BITS=8
- String parameter (possible values: SHA256, SHA512, SHA3, KECCAK, POSEIDON): SECURITY_PARAMETER_HASH=SHA256

You can change the names of the parameters if you know a better way to name them.

If any changes required in the backend part, please create an issue in the [proof-market-repository](https://github.com/NilFoundation/proof-market-v2/) and mention the created issue below this line.

**Comment by akokoshn** [comment]
no need more, due to make these parameters dynamic: https://github.com/NilFoundation/crypto3-zk/issues/286

**Comment by akokoshn** [comment]
Still need to modify scripts after enable https://github.com/NilFoundation/crypto3-zk/issues/286, so blocked for now
Definition of ready:

1. https://github.com/NilFoundation/crypto3-zk/issues/286
2. Way for pass values of arithmetization params

**Comment by akokoshn** [comment]
no need to modify scripts (arithmetization parameters pass throw assignment table file)
