### ISSUE TITLE
Keep just `auth.json` but not the basic user credentials

### ISSUE THREAD

**Issue by NickVolynkin** [NilFoundation/proof-market-toolchain#78]
# Current workflow

1. User registers with `./scripts/signup.py`, script saves credentials in `./scripts/.user` and `./scripts/.secret`.
	* Alternatively, user registers in the Web UI and manually saves credentials in in `./scripts/.user` and `./scripts/.secret`.
3. User authenticates with `./scripts/auth_tools.py`, script saves JSON web token in `./auth.json`
4. Other scripts use the JSON web token from `./auth.json`.

There's a number of problems here:

1. It's very unsafe, and users can lose their credentials by committing them in git.
2. Working with docker requires mounting a lot of files:
    ```
    docker run -it --rm \
      ...
      --volume $(pwd)/.config/.user:/proof-market-toolchain/scripts/.user \
      --volume $(pwd)/.config/.secret:/proof-market-toolchain/scripts/.secret \
      --volume $(pwd)/.config/auth.json:/proof-market-toolchain/auth.json \
      ...
    ```

# Proposed workflow

1. User registers with `./scripts/signup.py` on in WebUI and saves their credentials elsewhere: in a password manager, in memory, on a sticky note, whatever.
2. User runs `./scripts/auth_tools.py`, the script prompts for credentials, gets a JSON web token, and saves it in `~/.config/proof-market/auth.json`.
3. Other scripts use the JSON web token from that location.

---

Further on and out of scope of this issue, we'll make the following changes:

* The `proof-producer` binary will look for its configuration file somewhere under `/etc/proof-market/config.ini`
* Everything with a configuration or auth file will have optional `--config` and `--auth` parameters.

**Comment by alexandra-mara** [comment]
*Subscribing*

**Comment by NickVolynkin** [comment]
Turns out, JWT token is temporary and users need to keep the `.user` and `.secret` files. Things will change before we go to production, we will use a vendor solution.

**Comment by NickVolynkin** [comment]
Turns out, JWT token is temporary and users need to keep the `.user` and `.secret` files. Things will change before we go to production, we will use a vendor solution.
